### ISSUE TITLE
make the footnotes active

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#12]
footnote references should be active - either as links to footnotes or as popups of footnote text

**Comment by kirlat** [comment]
There is a 8b7d703f28d0dfbe3a0667d27aafa3db5f9da79b commit in [webextension](https://github.com/alpheios-project/webextension) that should solve it. Since table cells have a hover effect that highlights rows and columns, a popover with footnotes opens on click. Each popover has a individual close button. 

Several footnotes popovers can be open simultaneously. That might create an interesting possibilities when a user would like to compare footnotes to several suffixes, but I don't know if there will be any use for such scenarios.

**Comment by balmas** [comment]
this is done.
