### ISSUE TITLE
no matching on paradigm subtables

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#152]
no match for ἱκέσθαι 
also, for εἶναι"  we do not have a match in the table

**Comment by balmas** [comment]
Hmm. I think maybe we didn't implement matching on the supplementary paradigm tables. ἱκέσθαι and εἶναι are both matches into  those rather than the main paradigm table. @kirlat is that a correct analysis?

**Comment by kirlat** [comment]
I checked `ἱκέσθαι` and it seems that the following is happening.

In order to be a match, all features of a table cell must match features of the inflection. This is an algorithm we're using for a main table. 

For this particular case, each data cell of supplementary table has the following features:
0: "number"
1: "case"
2: "gender"
3: "part of speech"

Inflection, however, has different set of features that does not include all features of a cell:
0: "full form"
1: "part of speech"
2: "tense"
3: "voice"
4: "mood"
5: "stemtype"
6: "word" 

"Number", "case", and "gender" features are missing from an inflection. That's why there never can be a match.

I'm wondering if we should offer a different matching algorithm for supplementary tables?

**Comment by balmas** [comment]
ah probably yes. I'm tempted to defer this one.

**Comment by balmas** [comment]
postponing.

**Comment by balmas** [comment]
another test case from #207 οἴκοι is 3rd person sing. PERF. OPT. ACT. we don't have a match in the PERFECT ACTIVE SYSTEM inflection table. Any verb in the Optative (simple) table does not have a match.
