### ISSUE TITLE
support full forms as well as suffixes

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#17]
The Latin irregular verb tables use full form information rather than suffixes, and the tables are associated with specific lemmas. This will also be the case for pronouns.

**Comment by balmas** [comment]
I think we can handle this in a general way by allow for form data as well as suffix data for any part of speech and use logic which first checks to see if there is form data for the lemma associated with an inflection. If form data exists, we can skip the step of looking for suffixes and instead present the user with a view that is specific to the lemma and form.   

Most of the matching logic remains the same, but we need to be able to distinguish whether we are working with suffixes or forms in order to select the right matching algorithm.  

A start on this is coded in b028d46cfcb9e3d3078dec998baddf512419e25a

Some notes on the code in that commit:

For the moment I have kept the  method names and properties all referring to suffixes even if they might be retrieving forms. We may want to do a refactoring which renames this to something more general such as Item (I started on this but stopped because I wanted to be sure the approach makes sense first). I'm not sure if we want to rename the Suffix model object, or have a base Item model object with Form and Suffix subclasses. There is no real difference in behavior of a Form or Suffix but there is different behavior invoked depending upon which we are dealing with, so we do need to distinguish. For the moment I've addressed that by identifying these with a separate type parameter when passing things around across methods, and switching behavior based upon that. A subclassing approach is probably cleaner.

We will also have different views for forms than we do for suffixes. Working through creating those for the Latin irregular verbs will be the next step.

@kirlat I'd like your thoughts on what I've done so far and these comments before I proceed to the views.

**Comment by kirlat** [comment]
As per discussion in Slack:
The following app architecture would probably the best solution that will provide most flexibility.

Homonym/Lexeme/Lemma objects should carry all the information about what type of word they represent (regular/irregular).

If not all this data be available from the third-party service, a morphological analyzer adapter
should probably deduct it from the input it gets from third-party services or use Language Model as
a reference. A morphological analyzer library should be not just an adapter to a third-party sources, but rather a full-fledged service that will provide as complete word analysis as possible. For that, it should use
inputs from third-party services, language reference information from a Language Model, whatever else it has access to in order to return full analysis information to whoever requests it.

A Language Model should be a single source of truth of reference information about a language, except
for inflection tables related data that should belong to a inflection tables library.

Inflection tables have two important parts that provide data to the user:
  a. A LanguageDataset, that provides inflection and other info in a data format, and
  b. A ViewSet, that provides tables (and not only tables, as with footnotes) related to a particular word.

A user should supply a homonym to the inflections library, and get back data either in data format
(using a LanguageDataset), or in a visual form (using a ViewSet). If user
wants graphical data only, it would make sense for user to call a ViewSet directly, using homonym,
and a ViewSet would internally call Language Dataset to get data necessary to build views.

For that we can do the following changes to the inflection tables:
1. Make InflectionData more generic so it would keep suffixes/full forms or both if necessary. It can have properties that will store suffixes (if a word should have any) and properties for full forms. Right now it groups items by part of speech, we should add grouping by type of data (suffixes/full form). We should make it flexible to be able to support even more categorizations for the future and use smart getters to get only suffixes or any other particular type of data.
2. In LanguageDataset, store suffixes and full forms separately in different properties.
4. In LanguageDataset, add getFullForms() function that will work together with getSuffixes()
5. Create a universal getLexicalData(homonym) function that, depending on homonym data, will return 
a LexicalData object with either suffixes, or full forms, or both.
6. For Views, I think a getViews() function should take a homonym as an argument and return
whatever views need to be shown for this homonym's lexemes. For that, getViews() should use LanguageDataset and other libraries behind the scenes.

 `LanguageDataset.getData(homonym)` should return data in a data format and `ViewSet.getViews(homonym)` should return data required for a visual representation (or a visual representation elements itself). So user, depending on what info he/she needs, calls one or the other function, or both.

getViews() should be returning data grouped into tables. There should be two layers of data processing in inflection tables lib. First, lower level, is a LanguageDataset. It finds matches and returns them along with other data of same kind. The second layer, a ViewSet, is build on top of a LanguageDataset. It should be grouping suffixes into table-like structures and return them for UI to render tables. Second layer is needed only for those clients that want a visual representation.

However, because of complexity and lack of a reactive framework like Vue.js view data right now is tightly coupled with an HTML code. That should be changed since we can use Vue.js for rendering more effectively.

There also should be a third layer that will generate a visual representation. Right now it is an inflections.vue component. Such component should be outside of inflection tables library. It's better to be grouped with other UI components. 

inflections.vue uses ViewSet as a data model in an MVC paradigm: it takes data from a ViewSet and uses it to build a UI. Right now ViewSet is not a 'pure' data model as it returns HTML, but with Vue.js we can change that. Then ViewSet would provide just data, and a Vue component would attach it to a template, and a Vue.js engine would render the  whole thing.

**Comment by balmas** [comment]
Additional note, we may want to consider presentations other than tables for the View Sets. E.g. see https://github.com/alpheios-project/data-models/blob/master/src/language_model.js#L200-L311

**Comment by balmas** [comment]
reopening this .. I thought we had finished full form tables but they aren't actually working yet

**Comment by balmas** [comment]
the support for full forms is there. Individual items have been open to track the individual tables that need to be added or updated to use this feature.
