### ISSUE TITLE
linked participle tables for sum is not being filtered by lemma properly

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#198]
I did initially report this issue in #187 then I realized that it's valid for all tables.

**Comment by balmas** [comment]
oh, that's very weird. I think something went wrong with the build. I have rebuilt the memleaks2 branch and it seems to be working for me now. Can you get the latest version from https://github.com/alpheios-project/webextension/tree/memleaks2/dist and see if it still occurs?
Thank you!

**Comment by balmas** [comment]
please retest in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-17/dist

**Comment by monzug** [comment]
they do display correctly now but the verb participle of sum has all the entries of the irregular participle
see screenshot

![sum](https://user-images.githubusercontent.com/41396793/46361269-291df780-c63b-11e8-8190-74b913787dfb.JPG)

**Comment by balmas** [comment]
ok thanks, will look at this.

**Comment by balmas** [comment]
it seems that the problem is with the construction of the participle view as a linked table.

If you lookup `futurus` which is a participle of `sum`, you correctly get the participle table filtered to only the data for `sum`:
[
![screenshot from 2018-10-02 13-58-28](https://user-images.githubusercontent.com/644870/46367360-4fe42a00-c64b-11e8-9f96-560c256fcc43.png)
](url)

But if you lookup `sum`, the linked participle table contains the participles for all irregular verbs:
![screenshot from 2018-10-02 13-59-53](https://user-images.githubusercontent.com/644870/46367411-7ace7e00-c64b-11e8-9d70-d62e6b3a27a1.png)

**Comment by balmas** [comment]
Note that this does NOT affect all irregular verbs. `fero` and `volo` both show the correctly filtered participle table.

**Comment by balmas** [comment]
fixed in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-18/dist

**Comment by monzug** [comment]
yes, it was only for sum. checked all the irregular participles, looks ok
