### ISSUE TITLE
morphology should not be matching if there were NO common features

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#217]
Lookup for δύω  matches all endings in the numeral table. We are missing the information on case, gender and number.
see screenshot
![numeral](https://user-images.githubusercontent.com/41396793/46793624-33638400-cd14-11e8-99be-5ddefba7ff3d.JPG)

**Comment by balmas** [comment]
that's interesting. it looks like somehow the morphology data from the morph-client isn't making it to the homonym object properly. will investigate.

**Comment by balmas** [comment]
Actually, I was wrong, the parser results are NOT showing any useful inflection data for this particular form:

```
<entry uri="">
<dict>
<hdwd xml:lang="grc">δύο</hdwd>
<pofs order="4">numeral</pofs>
</dict>
<infl>
<term xml:lang="grc">
<stem>δύω</stem>
</term>
<pofs order="4">numeral</pofs>
<dial>epic</dial>
<stemtype>numeral</stemtype>
<morph>indeclform</morph>
</infl>
</entry>
```

So we don't have any characteristics other than part of speech to match on.

I am not sure if the morph feature value in the parser outputs, 'indeclform' , indicates that this is an undeclined form.  If it *does* mean that then perhaps we could look for that feature and use it to tell us to not even try matching, but I think if we were to make that change it would need much testing because I am not really sure what the parser means by that.

@monzug what do you think is a reasonable way to handle matching when we just have none of the features required by the table. Maybe in that case, instead of matching all, we should match none?

**Comment by balmas** [comment]
@monzug not sure what to do with this one.

**Comment by monzug** [comment]
yes. I think the best would be no matching

**Comment by balmas** [comment]
ok, I changed the title of this to reflect what the issue really is.

**Comment by balmas** [comment]
ready for testing in https://github.com/alpheios-project/webextension/tree/v2.0.3.2/dist

**Comment by monzug** [comment]
much better. Thanks
