### ISSUE TITLE
add cell matching to greek paradigm tables

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#41]
We need the ability to show matches on inflection properties in the greek verb paradigm tables. A full match should be one which matches all features of the cell properties. A match on the cell value is not required for a full match since the paradigms are exemplars.

**Comment by kirlat** [comment]
Will add that. Since paradigm tables are using Vue, will need to add a matching logic there.

**Comment by kirlat** [comment]
I implemented this with highlighting a whole cell, as in V1.

In "regular" inflection tables we highlight a word, not a cell, because a cell can have multiple endings and we need to indicate which one is a match. Such situation is not possible in paradigm tables, where we match a cell (a set of features), so we can allow ourselves to select a whole cell. I think it will be more noticeable and easier to catch at first glance.

However, if we need to follow the style of "regular" infection tables, we can change it to select a word instead of a cell.

**Comment by balmas** [comment]
I think highlighting a whole cell here is fine.

**Comment by balmas** [comment]
this appears to be working well

**Comment by balmas** [comment]
@kirlat cell matching in the paradigms seems to be gone again in the latest build from master (using github:alpheios-project/inflection-tables#011aba19e35f331be4121208dcd906419b004e06 and github:alpheios-project/components#4eb8394f9ba62ceba8be5316c452d13ad34a6b2e)

Do you see the same?

**Comment by kirlat** [comment]
Yes, I see the same. Will fix.

**Comment by kirlat** [comment]
Seems to be a merge artefact. Should be fixed with 5954daedf0aedccafda2ad2b13120c750fcf3789.

**Comment by kirlat** [comment]
Changes should be in master as of now
