### ISSUE TITLE
Latin Adjective inflection table doesn't show values for combinated declensions and doesn't correctly show fullMatch for it

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/inflection-tables#59]
I tested on the adjective - **beatum**

In the old version it has declension **first\second** with fullMatch
![image](https://user-images.githubusercontent.com/12377640/42885387-247b88ec-8ae4-11e8-8fb7-d6606a38c6fb.png)

In the new version 

1) it hasn't combinated declension
![image](https://user-images.githubusercontent.com/12377640/42885461-5a86c2b2-8ae4-11e8-923b-660483b1ec0b.png)

2) if check **matchingValue** for declension there won't be matched, because
    inflection from lexeme has value **1st** or **2nd** and isMultiple = false
    suffixFeature declension has [1st, 2nd] - but it won't check in array - as it is not Multiple - so there is no match here

**Comment by kirlat** [comment]
@balmas:
The latest commit 1d76c997fac99927f71af03f8548be2a35bf206d should fix all issues known to me with Latin and Greek table formatting and match highlighting. The only thing that is probably not working are tables for gerundive and supine. They are rarely used, I hope. I tried to push changes to major POFSs as fast as possible hoping that minor ones can be fixed later. Otherwise it would probably take forever to complete the change.

I was definitely not able to test all scenarios because of their sheer volume and multitude of variations. The understanding that tables in V1 are not always correct and we cannot blindly rely on them complicated the matter further.

It would be great if @monzug can be able to start testing this release. She probably has better experience in this than I am. For whatever issues be found we can create separate tickets and solve them on a case by case basis.

In order to test this it should be enough to get https://github.com/alpheios-project/inflection-tables/tree/issue-inflection-tables-59 branch of webextension. Please note that this build does not include fixes for issues 61 and 62 as they are not reviewed yet and are not merged to `master`.

Sorry for broken tests. There were many changes in this release, and updating tests would take some time. I was rushing to push this build before my vacation in order for it to be tested. I will update test at first possibility, I promise!

**Comment by irina060981** [comment]
I have tried to check it but this version doesn't render inflections button on popup and throw an error:
![image](https://user-images.githubusercontent.com/12377640/43877597-281cacd2-9bde-11e8-81f7-788d60b0d068.png)
![image](https://user-images.githubusercontent.com/12377640/43877607-335da66e-9bde-11e8-85dc-00d850f3cfc9.png)

**Comment by balmas** [comment]
@irina060981 I'm not getting that error with this build of the webextension.  Which version did you install exactly?

**Comment by balmas** [comment]
I have merged the inflection tables changes for issues 61 and 62 now and rebuilt the  https://github.com/alpheios-project/inflection-tables/tree/issue-inflection-tables-59 branch of webextension so that it includes that.

So @monzug it should be ok for you to get this build and start testing now. It should include the fixes for this issue as well as 61 and 62.

**Comment by irina060981** [comment]
I have checked and found that I haven't uploaded issue-inflection-tables-59 branch from data-models - it caused a error.
So if update both - 
https://github.com/alpheios-project/inflection-tables/tree/issue-inflection-tables-59
https://github.com/alpheios-project/data-models/tree/issue-inflection-tables-59

Everything works :)

**Comment by monzug** [comment]
I will open separate tickets for issues found testing this bug. We do show the table for 1st and 2nd adj decl.
