### ISSUE TITLE
paradigm rule matchOrder should be used to filter matches

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#62]
different paradigm matching rules have different orders. When multiple paradigms match, only those with the highest order should be included. 

I think this bug is why we're getting more matches for οὖσᾰ as reported in #51

**Comment by balmas** [comment]
yes that is correct. thanks!

**Comment by kirlat** [comment]
How should that work across multiple inflections? Let's say we have two inflection each having two matching paradigms:
```
Inflection A
   paradigm 1 matchOrder 15
   paradigm 2 matchOrder 12
Inflection B
   paradigm 3 matchOrder 12
   paradigm 4 matchOrder 9
```
Shall we, in this case, show a table for paradigm 1 only (as having the highest matchOrder among paradigms of all inflections), or shall we show paradigm 3 as well (so that both inflections A and B be represented with their highest matching paradigms)?

**Comment by kirlat** [comment]
I updated it so that it will return paradigms with the highest matchOrder rules across all matching paradigms. So, for the example above it will return paradigm 1 only as it has the rule with the highest matchOrder, 15. This seems to be matching the logic from V1.

**Comment by balmas** [comment]
@monzug can you test this in the https://github.com/alpheios-project/webextension/tree/issue-inflection-tables-61-62 branch ?  You can download it from https://github.com/alpheios-project/webextension/archive/issue-inflection-tables-61-62.zip

**Comment by balmas** [comment]
i think this was tested with #61 but @monzug can you confirm?

**Comment by monzug** [comment]
yes.
