### ISSUE TITLE
Inflection table for sum & fero (irregular verbs): side effect of recent changes? 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#83]
the irregular verb table (sum in this case) has only the indicative mood and has all the irregular verbs listed. see screenshot (both firefox and chrome).
more, fero: the verb drop-down has two verb-irregular. one of these two option generates the inflection table with the verbal forms mixed up.
![screenshot_2018-08-11 ego in english with contextual examples - mymemory](https://user-images.githubusercontent.com/41396793/44033888-bb9e03d6-9ed9-11e8-8e6c-204c650cf068.png)
![screenshot_2018-08-13 slogan tungkol sa pi - english - tagalog translation and examples 1](https://user-images.githubusercontent.com/41396793/44033889-bbd214c8-9ed9-11e8-92b3-ebd5b759a303.png)
![screenshot_2018-08-13 slogan tungkol sa pi - english - tagalog translation and examples](https://user-images.githubusercontent.com/41396793/44033891-bc0166f6-9ed9-11e8-839f-1a4c7ba74b84.png)

**Comment by kirlat** [comment]
This should be fixed with the latest build of webextension: alpheios-project/webextension@e8042e6d4521ff0c7068c0666cafda3e671bcc5e
It does solve issue with showing extra verb forms in irregular verb tables and with showing an extra table for "fero".

It does show only indicative mood for "sum" because, by default, we show tables collapesd, and indicative mood is the only one that has matches. Clicking on the "Full table" button should show other moods;
![image](https://user-images.githubusercontent.com/18631055/44459742-c557e600-a61b-11e8-9a6b-a78a4c5be8f6.png)
Please let me know if this behavior is correct because if not, we can change it to suit our needs.

**Comment by kirlat** [comment]
PS: to test this, install a code from `webextension` with `issue-inflection-tables-59` tag.

**Comment by balmas** [comment]
assigning to @monzug to retest with latest `issue-inflection-tables-59 ` build of the webextension

**Comment by monzug** [comment]
tested with latest build. it works fine as described in the fix.  Thanks.
However, for some reason the font for the inflection table drop-down are really small. any change here?

**Comment by monzug** [comment]
tested in a bunch of site and fonts are ok. close this one
